---


- name: Test routers_commands
  hosts: yourhosts
  connection: network_cli
  remote_user: youruser
  gather_facts: false
  tasks:
  - name: "Ansible is working"
    routeros_command:
      commands: /log info "ansible is working"

  - name: getting identity
    routeros_command:
      commands: ;put [/system identity get value-name=name ]
    register: identity

  - name: getting version
    routeros_command:
      commands: ;put [/system resource get value-name=version ]
    register: version

  - name: set channel
    routeros_command:
      commands: /system package update set channel=bugfix
    register: seting channel to bug-fix/longterm

  - pause: seconds=3

# your shouldnt be using the admin user but here you are. 

  - name: setting new admin pass
    routeros_command:
      commands: 
        - /user set [find where name="admin"] password="usestrongpasswordhere"
    register: newadminpass

  - name: log message
    routeros_command:
      commands: /log info "admin password has been updated."

  - debug:
      msg: "{{ identity.stdout}}{{ version.stdout}}"

  - name: line insert
    lineinfile: path=/tmp/setadminpass.txt
                line="{{ identity.stdout}}{{ version.stdout}}"
                insertbefore=BOF
